#!/usr/bin/python
# -*- coding: utf-8 -*-
import cgitb
cgitb.enable()

class Bill:
	#Constructor that builds a bill object given an ordered list of strings
	#generated by the database interface (this leaves vote_tally empty by
	#default)
	def __init__(self, params):
		self.id = params[0]
		self.session = params[1]
		self.roll = params[2]
		self.vote_date = params[3]
		self.type = params[4]
		self.question = params[5]
		if len(params)!=6:
			self.yea_votes = params[6]
			self.nay_votes = params[7]
			self.abstaining = params[8]
			self.absent = params[9]
		else:
			self.yea_votes = []
			self.nay_votes = []
			self.abstaining = []
			self.absent = []

	#Generates a link to the bill’s page with the properly formatted HTML text
	#and returns it as a string.
	def getBillLink(self):
		HtmlString = ""
		return HtmlString

	def getId(self):
		return self.id

	def getSession(self):
		return self.session

	def getRoll(self):
		return self.roll

	def getVoteDate(self):
		return self.vote_date

	def getType(self):
		return self.type

	def getQuestion(self):
		return self.question

	def getYea_Votes(self):
		return self.yea_votes

	def getNay_Votes(self):
		return self.nay_votes

	def getAbstaining(self):
		return self.abstaining

	def getAbsent(self):
		return self.absent

