#!/usr/bin/python
# -*- coding: utf-8 -*-

class Bill:
	#Constructor that builds a bill object given an ordered list of strings
	#generated by the database interface (this leaves vote_tally empty by
	#default)
	def __init__(self, id, params):
		self.id = params[0]
		self.session = params[1]
		self.roll = params[2]
		self.vote_date = params[3]
		self.type = params[4]
		self.question = params[5]
		if len(params)!=6:
			self.yea_votes = params[6]
			self.nay_votes = params[7]
			self.present = params[8]
			self.not_voting = params[9]

	#Speaks to the database interface and populates vote_tally with the
	#requisite senators and their votes from the database
	def populateVotes(self):
		#do stuff

	#Generates a link to the bill’s page with the properly formatted HTML text
	#and returns it as a string.
	def generateBillLink(self):
		HtmlString = ""
		return HtmlString

	#Gets the bill's name
	def getName(self):
		return self.name

	#Gets the bill's id tag
	def getId(self):
		return self.id

	#Gets the bill's HR tag
	def getHr(self):
		return self.hr

	#Gets the date on which the bill was voted.
	def getDate(self):
		return self.date

	#Gets the congress that voted on the bill.
	def getCongress(self):
		return self.congress

	#Gets the bill's description.
	def getDescription(self):
		return self.description

	#Returns the vote tally: a two-dimensional list of the votes; vote_tally[0] is a list of
	#senators, vote_tally[1] is a list of strings representing votes:
	#"Yea", "Nay", "Absent", or "Abstain"
	def getVoteTally(self):
		return self.vote_tally