#!/usr/bin/python
# -*- coding: utf-8 -*-

import cgitb
cgitb.enable()

class Committee:
    """An object that stores the database's information on a committee."""

    def __init__(self, params):
        # Takes a given ordered list of strings generated by the database
        # interface and generates an object.
        self.id = params[0]
        self.name = params[1]
        self.super_committee = params[2]
        self.session_of_congress = params[3]

        # [[SenObj, name], [SenObj, name]]
        if (len(params) == 5):
            self.senators = params[4]
        else:
            self.senators = [[]]

    def getCommitteeLink(self):
        # Generates an HTML link to the committee's page and returns it as a
        # string.
        HTML_string = ('<a href = "index.py?page_type=committee&committee='
                    + str(self.getId()) + '">' + self.getName() + '</a>')
        return HTML_string

    def getId(self):
        return self.id

    def getName(self):
        return self.name

    def getSuperCommittee(self):
        return self.super_committee

    def getSuperCommitteeLink(self):
        HTML_string = ('<a href = "index.py?page_type=committee&committee='
                    + str(self.getSuperCommittee()) + '">' + 'Super-Committee'
                    + '</a>')
        return HTML_string

    def getSession(self):
        return self.session_of_congress

    def getSenators(self):
        return self.senators