#!/usr/bin/python
# -*- coding: utf-8 -*-

class Senator:
	#Constructor that builds a senator object from the senators id and an 
	#array of string parameters containing the variables from the senator as
	#generated by the database interface
	#birthday might be a date? ot
	def __init__(self, id_num, last, first, birthday, gender, party, wiki, current):
		self.id = id_num
		self.last = last
		self.first = first
		self.birthday = birthday
		self.gender = gender
		self.party = party
		self.wiki = wiki
		self.current = current #Boolean value, true means a current senator

	#Generates a link to the senator’s page with the properly formatted text and
	#returns it as a string(e.g. (R-AK) Richard White ).
	def generateSenatorLink(self):
		htmlLink = ""
		return htmlLink

	def getFirst(self):
		return self.first

	def getLast(self):
		return self.last

	def getName(self):
		return self.first + " " + self.last

	def getId(self):
		return self.id

	def getState(self):
		return self.state

	def getCongressesServed(self):
		return self.congresses_served

	def getParty(self):
		return self.party