#!/usr/bin/python
# -*- coding: utf-8 -*-

class Senator:
	#Constructor that builds a senator object from the senators id and an 
	#array of string parameters containing the variables from the senator as
	#generated by the database interface
	def __init__(self, id, params):
		#do stuff; initialize variables


	#Generates a link to the senator’s page with the properly formatted text and
	#returns it as a string(e.g. (R-AK) Richard White ).
	def generateHtmlNameLink(self):
		htmlLink = ""
		return htmlLink

	#Returns the senator's name.
	def getName(self):
		return this.name

	#Returns the senator's id tag.
	def getId(self):
		return this.id

	#Returns the senator's home state.
	def getState(self):
		return this.state

	#Returns the list of congresses in which the senator has served.
	def getCongressesServed(self):
		return this.congresses_served

	#Returns the senator's party
	def getParty(self):
		return this.party